//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public decimal MESSAGE_ID { get; set; }
        public Nullable<decimal> GROUP_ACCOUNT_ID { get; set; }
        public string TEXT { get; set; }
    
        public virtual GROUP_ACCOUNTS GROUP_ACCOUNTS { get; set; }
    }
}
